Config.TargetBones = {
["Engine"] = {
        bones = {
            "engine",
        },
        options = {
            {
                type = "client",
                event = "qb-carparts:client:enginelvl0",
		        item = "enginelvl0",
                icon = "fas fa-car",
                label = "Install Stock Engine",
                job = mechanic,
            },
            {
                type = "client",
                event = "qb-carparts:client:enginelvl1",
		        item = "enginelvl1",
                icon = "fas fa-car",
                label = "Install Engine Level 1",
                job = mechanic,
            },
            {
                type = "client",
                event = "qb-carparts:client:enginelvl2",
		        item = "enginelvl2",
                icon = "fas fa-car",
                label = "Install Engine Level 2",
                job = mechanic,
            },
            {
                type = "client",
                event = "qb-carparts:client:enginelvl3",
		        item = "enginelvl3",
                icon = "fas fa-car",
                label = "Install Engine Level 3",
                job = mechanic,
            },
            {
                type = "client",
                event = "qb-carparts:client:enginelvl4",
		        item = "enginelvl4",
                icon = "fas fa-car",
                label = "Install Engine Level 4",
                job = mechanic,
            },
            {
                type = "client",
                event = "qb-carparts:client:noturbo",
		        item = "noturbo",
                icon = "fas fa-car",
                label = "Remove Turbo",
                job = mechanic,
            },
            {
                type = "client",
                event = "qb-carparts:client:turbo",
		        item = "turbo",
                icon = "fas fa-car",
                label = "Install Turbo",
                job = mechanic,
            },
            {
                type = "client",
                event = "qb-carparts:client:translvl0",
		        item = "translvl0",
                icon = "fas fa-car",
                label = "Install Stock Transmission",
                job = mechanic,
            },
            {
                type = "client",
                event = "qb-carparts:client:translvl1",
		        item = "translvl1",
                icon = "fas fa-car",
                label = "Install Transmission Level 1",
                job = mechanic,
            },
            {
                type = "client",
                event = "qb-carparts:client:translvl2",
		        item = "translvl2",
                icon = "fas fa-car",
                label = "Install Transmission Level 2",
                job = mechanic,
            },
            {
                type = "client",
                event = "qb-carparts:client:translvl3",
		        item = "translvl3",
                icon = "fas fa-car",
                label = "Install Transmission Level 3",
                job = mechanic,
            },
            {
                type = "client",
                event = "qb-carparts:client:translvl4",
		        item = "translvl4",
                icon = "fas fa-car",
                label = "Install Transmission Level 4",
                job = mechanic,
            },


        },
        distance = 1.0
    },

["Tire"] = {
        bones = {
		'wheel_lf', 
		'wheel_lr',
		'wheel_rf', 
		'wheel_rr',
        },
        options = {
            {
                type = "client",
                event = "qb-carparts:client:usetirekit",
		        item = "stock_tires",
                icon = "fas fa-car",
                label = "Change Tire",
            },
            {
                type = "client",
                event = "qb-carparts:client:brakeslvl0",
		        item = "brakeslvl0",
                icon = "fas fa-car",
                label = "Install Stock Brakes",
                job = mechanic,
            },
           {
                type = "client",
                event = "qb-carparts:client:brakeslvl1",
		        item = "brakeslvl1",
                icon = "fas fa-car",
                label = "Install Brakes Level 1",
                job = mechanic,
            },
           {
                type = "client",
                event = "qb-carparts:client:brakeslvl2",
		        item = "brakeslvl2",
                icon = "fas fa-car",
                label = "Install Brakes Level 2",
                job = mechanic,
            },
           {
                type = "client",
                event = "qb-carparts:client:brakeslvl3",
		        item = "brakeslvl3",
                icon = "fas fa-car",
                label = "Install Brakes Level 3",
                job = mechanic,
            },
           {
                type = "client",
                event = "qb-carparts:client:shockslvl0",
		        item = "shockslvl0",
                icon = "fas fa-car",
                label = "Install Stock Shocks",
            },
           {
                type = "client",
                event = "qb-carparts:client:shockslvl1",
		        item = "shockslvl1",
                icon = "fas fa-car",
                label = "Install Shocks Level 1",
                job = mechanic,
            },
           {
                type = "client",
                event = "qb-carparts:client:shockslvl2",
		        item = "shockslvl2",
                icon = "fas fa-car",
                label = "Install Shocks Level 2",
                job = mechanic,
            },
           {
                type = "client",
                event = "qb-carparts:client:shockslvl3",
		        item = "shockslvl3",
                icon = "fas fa-car",
                label = "Install Shocks Level 3",
                job = mechanic,
            },
           {
                type = "client",
                event = "qb-carparts:client:shockslvl4",
		        item = "shockslvl4",
                icon = "fas fa-car",
                label = "Install Shocks Level 4",
                job = mechanic,
            },
        },
        distance = 1.0
    },

}